services:
  db:
    image: mysql:latest
    container_name: quizzes_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: quizzes
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - quizzes_network

networks:
  quizzes_network:
    driver: bridge

volumes:
  mysql_data: